version: '3'
services:
  sql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: yourStrong(!)Password
    networks:
    - "feedyre"
    volumes:
      - "mssqlsystem:/var/opt/mssql"
      - "mssqluser:/var/opt/sqlserver"
    restart: always
  main_web: 
    container_name: main_web
    image: karmraks/feedyre_api
    ports: 
      - "8000:8080"
    networks:
    - "feedyre"
    restart: always
  frontend_ng: 
    container_name: frontend_ng
    image: karmraks/feedyre_ng
    ports: 
      - "80:8080" 
    networks:
    - "feedyre"
    restart: always 
networks:
  feedyre:
    driver: bridge
volumes:
  mssqlsystem:
    external: true
  mssqluser: 
    external: true