// <auto-generated />
using System;
using FEEDYRE.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEEDYRE.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240104202506_SeedUserWithRoles")]
    partial class SeedUserWithRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FEEDYRE.Core.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550c9fb1-ba46-44ac-bc43-0e32cb1b80ad"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("8da6bd0d-6e3f-4912-a97a-e0c814ef5528"),
                            Name = "Sensei"
                        },
                        new
                        {
                            Id = new Guid("da526b84-4281-4b90-a853-ce6fcc26163e"),
                            Name = "Trainee"
                        });
                });

            modelBuilder.Entity("FEEDYRE.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b31966e3-1d47-420c-b62f-366a3d950991"),
                            Email = "admin",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("FEEDYRE.Core.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("995656e9-3c9e-480d-9847-dbe058aea3ff"),
                            RoleId = new Guid("550c9fb1-ba46-44ac-bc43-0e32cb1b80ad"),
                            UserId = new Guid("b31966e3-1d47-420c-b62f-366a3d950991")
                        });
                });

            modelBuilder.Entity("FEEDYRE.Core.Models.UserRole", b =>
                {
                    b.HasOne("FEEDYRE.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEEDYRE.Core.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FEEDYRE.Core.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
