# name: Build
# on:
#   push: 
#     branches: [main]
#   pull_request: 
#     branches: [main]

# jobs:
#   build_main_api: 
#     name: Build Main API [.net]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Log in Docker HUB
#         uses: docker/login-action@v1
#         with:
#           username: karmraks
#           password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#       - name: Build docker 
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: karmraks/feedyre_api
#   build_ng: 
#     name: Build Angular
#     runs-on: ubuntu-latest
#     steps:
#         - name: Checkout
#           uses: actions/checkout@v2
#         - name: Log in Docker HUB
#           uses: docker/login-action@v1
#           with:
#             username: karmraks
#             password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#         - name: Build docker 
#           uses: docker/build-push-action@v2
#           with:
#             context: ./FEEDYRE.Ng
#             file: ./FEEDYRE.Ng/Dockerfile
#             push: true
#             tags: karmraks/feedyre_ng
  # deploy: 
  #   runs-on: ubuntu-latest
  #   needs: [build_main_api, build_ng]
  #   steps: 
  #     - name: Login via SSH and call docker-compose 
  #       uses: appleboy/ssh-action@v0.1.3
  #       with: 
  #         host: 167.99.136.88
  #         username: root
  #         password: ${{ secrets.DIGITAL_OCEAN_DROPLET_PASSWORD }}
  #         script: |
  #          cd /home
  #          docker-compose down
  #          docker-compose pull
  #          docker-compose up --detach